#!/bin/sh

CMD="$1"
TESTING="$2"

case "$CMD" in
    start)
        mcstartservers $TESTING
        ;;
    stop)
        mcstopservers $TESTING
        ;;
    status)
        mcstatusservers $TESTING
        ;;
esac
