#!/usr/bin/env bash

function is_running() {
    ps -eo "pid,command" | grep "$1" | grep "$2" | grep -v grep | sed 's/^[ ]*//' | cut -f1 -d' '
}

function docker_instance_running() {
    docker ps -a | grep "$1\$" | grep "Up "
}

function build_mcstored()
{
    if [ ${COMPILE_MCSTORE} = "t" ]; then
        (cd ${MCSTORE_SRC}; make server)
        cp ${MCSTORE_SRC}/server/mcstore/main/mcstored ${MCSTOREDBIN}
    fi
}

function must_be_mcuser() {
    if [ "$USER" != "$MCUSER" ]; then
        if [ "$USER" != "root" ]; then
            echo "You must be ${MCUSER} or root to perform this action..."
            exit 1
        fi
    fi
}

function start_es() {
    R=$(docker_instance_running ${MC_ES_NAME})
    if [ "$R" = "" ]; then
        echo "Starting Elasticsearch instance ${MC_ES_NAME} ($SERVERTYPE)..."
        docker start ${MC_ES_NAME}
    fi
}

function stop_es() {
    echo "Stopping Elasticsearch ($SERVERTYPE)..."
    R=$(docker_instance_running ${MC_ES_NAME})
    if [ "$R" != "" ]; then
        docker stop ${MC_ES_NAME}
        echo "  Stopped Elasticsearch docker instance ${MC_ES_NAME}"
    fi
}

function start_faktory() {
    if [ "$(uname)" = "Darwin" ]; then
        R=$(ps -eo "pid,command" | grep faktory | grep -v tail | grep -v grep | grep -v bash)
        if [ "$R" = "" ]; then
            echo "Starting Faktory from command line..."
            faktory > ${MC_LOG_DIR}/faktory.out.${SERVERTYPE} 2>&1&
            sleep 1
        fi
    else
        R=$(docker_instance_running ${MC_FAKTORY_NAME})
        if [ "$R" = "" ]; then
            echo "Starting Faktory docker instance ${MC_FAKTORY_NAME}..."
            docker start ${MC_FAKTORY_NAME}
            sleep 1
        fi
    fi
}

function stop_faktory() {
    if [ "$(uname)" = "Darwin" ]; then
        echo "Stopping Faktory ($SERVERTYPE); using command line ..."
        RPID=$(ps -eo "pid,command" | grep faktory | grep -v tail | grep -v grep | grep -v bash | head -1 | sed 's/^[ ]*//' | cut -f1 -d' ')
        if [ "$RPID" != "" ]; then
            kill ${RPID}
            echo "  Stopped Faktory from command line (${RPID})..."
        fi
    else
        echo "Stopping Faktory instance (${MC_FAKTORY_NAME}) in docker..."
        docker stop ${MC_FAKTORY_NAME}
        echo "  Stopped Faktory docker instance ${MC_FAKTORY_NAME}"
    fi
}

function start_etl_faktory_worker() {
    R=$(is_running "run_worker" "$SERVERTYPE")
    if [ "$R" = "" ]; then
        echo "Starting ETL faktory worker ($SERVERTYPE)..."
        ./servers/etlserver/run_worker.sh $SERVERTYPE > ${MC_LOG_DIR}/mcetlfaktoryworker.out.${SERVERTYPE} 2>&1&
        sleep 1
    fi
}

function stop_etl_faktory_worker() {
    echo "Stopping etl faktory worker (${SERVERTYPE})..."
    ps -eo "pid,command" | grep "run_worker" | grep ${SERVERTYPE} | grep -v grep | sed 's/^[ ]*//' | cut -f1 -d' ' | while read line
    do
        kill ${line}
        echo "  Stopped etl faktory worker with pid ${line}"
    done
}

function start_etl_server() {
    R=$(is_running "mc_etlserver.py")
    if [ "$R" = "" ]; then
        echo "Starting mcetlserver (${SERVERTYPE})..."
        ./servers/etlserver/run_server.sh ${SERVERTYPE} > ${MC_LOG_DIR}/mcetlserver.out.${SERVERTYPE} 2>&1&
        sleep 1
    fi
}

function stop_etl_server() {
    echo "Stopping mcetlserver (${SERVERTYPE})..."
    ps -eo "pid,command" | grep "mc_etlserver.py" | grep -v grep | sed 's/^[ ]*//' | cut -f1 -d' ' | while read line
    do
        kill ${line}
        echo "  Stopped mcapiserver with pid ${line}"
    done
}

function start_rethinkdb() {
    R=$(is_running "rethinkdb" "driver-port $MCDB_PORT")
    if [ ! -d "${MCDB_DIR}" ]; then
        echo ${MCDB_DIR} does not exist, please create and restart
        exit 1
    fi

    if [ ! -w "${MCDB_DIR}" ]; then
        echo "${MCDB_DIR}" is not writable, please correct permissions and restart
        exit 1
    fi

    if [ ! -r "${MCDB_DIR}" ]; then
        echo ${MCDB_DIR} is not readable, please correct permissions and restart
        exit 1
    fi

    if [ "$R" = "" ]; then
        echo "Starting rethinkdb ($SERVERTYPE)..."
        (cd ${MCDB_DIR}; rethinkdb --driver-port ${MCDB_PORT} --cluster-port ${RETHINKDB_CLUSTER_PORT} --http-port ${RETHINKDB_HTTP_PORT} --daemon)
        scripts/db_running.py --port ${MCDB_PORT}
        echo "Setting up database..."
        scripts/dbcreate.py
        if [ ${TESTSERVER} != false ]; then
            if [ "$REINIT" = "t" ]; then
                echo "  Restoring from file $MCDB_FILE..."
                cp ${MCDB_FILE} ${MCDB_DIR}
                FILE=$(basename ${MCDB_FILE})
                rethinkdb restore ${MCDB_DIR}/${FILE} --connect localhost:${MCDB_PORT} --force
                if [ $? -ne 0 ]; then
                    rethinkdb restore ${MCDB_DIR}/${FILE} --connect localhost:${MCDB_PORT} --force
                fi
            fi
        fi
    fi
}

function stop_rethinkdb() {
    echo "Stopping rethinkdb ($SERVERTYPE)..."
    RPID=$(ps -eo "pid,command" | grep rethinkdb | grep "driver-port $MCDB_PORT" | grep -v grep | head -1 | sed 's/^[ ]*//' | cut -f1 -d' ')
    if [ "$RPID" != "" ]; then
        kill ${RPID}
        echo "  Stopped rethinkdb with pid ${RPID}"
    fi
}

function start_mcapiserver() {
    $(python -c 'import sys; exit(1) if (sys.version_info.major == 2 and sys.version_info.minor == 7) else exit(0)')
    PVCHECK=$?
    if [ ! "${PVCHECK}" == "1" ]; then
        echo "WARNING: mcapiserver must run under python 2.7"
        echo "WARNING: current version of python is $(python --version 2>&1)"
    fi
    R=$(is_running "mcapiserver.py" "p $MC_SERVICE_PORT")
    if [ "$R" = "" ]; then
        echo "Starting mcapiserver ($SERVERTYPE)..."
        ./mcapiserver.py -p ${MC_SERVICE_PORT} > ${MC_LOG_DIR}/mcapiserver.out.${SERVERTYPE} 2>&1&
        sleep 1
    fi
}

function stop_mcapiserver() {
    echo "Stopping mcapiserver (${SERVERTYPE})..."
    ps -eo "pid,command" | grep mcapiserver.py | grep "p $MC_SERVICE_PORT" | grep -v grep | sed 's/^[ ]*//' | cut -f1 -d' ' | while read line
    do
        kill ${line}
        echo "  Stopped mcapiserver with pid ${line}"
    done
}

function start_mcstored() {
    R=$(is_running "mcstored.forever.sh" "${SERVERTYPE}")
    if [ "$R" = "" ]; then
        echo "Starting mcstored ($SERVERTYPE)..."
        build_mcstored
        export MC_LOG_DIR
        export SERVERTYPE
        export MCSTOREDBIN
        ./mcstored.forever.sh ${SERVERTYPE} --http-port=${MCFS_HTTP_PORT} --mcdir=${MCDIR} --db-connect="localhost:$MCDB_PORT" --es-url=${MC_ES_URL} > /dev/null 2>&1&
        sleep 1
    fi
}

function stop_mcstored() {
    echo "Stopping mcstored ($SERVERTYPE)..."
    MCSTORED_PID=$(ps -eo "pid,command" | grep mcstored.forever.sh | grep "${SERVERTYPE}" | grep -v grep | sed 's/^[ ]*//' | cut -f1 -d' ')
    if [ "$MCSTORED_PID" != "" ]; then
        kill ${MCSTORED_PID}
        echo "  Stopped mcstored.forever.sh with pid $MCSTORED_PID"
    fi

    MCSTORED_PID=$(ps -eo "pid,command" | grep mcstored | grep "db-connect="localhost:$MCDB_PORT"" | grep -v grep | sed 's/^[ ]*//' | cut -f1 -d' ')
    if [ "$MCSTORED_PID" != "" ]; then
        kill ${MCSTORED_PID}
        echo "  Stopped mcstored with pid $MCSTORED_PID"
    fi
}

function start_mcapi() {
    R=$(is_running "servers/mcapi/mcapi.js" "p $MC_API_SERVICE_PORT")
    if [ "$R" = "" ]; then
        echo "Starting mcapi ($SERVERTYPE)..."
        nodemon --watch servers/mcapi --watch servers/lib servers/mcapi/mcapi.js -p ${MC_API_SERVICE_PORT} > ${MC_LOG_DIR}/mcapi.out.${SERVERTYPE} 2>&1&
        sleep 1
    fi
}

function stop_mcapi() {
    echo "Stopping mcapi ($SERVERTYPE)..."
    ps -eo "pid,command" | grep "mcapi.js" | grep "p $MC_API_SERVICE_PORT" | grep -v grep | sed 's/^[ ]*//' | cut -f1 -d' ' | while read line
    do
        kill ${line}
        echo "  Stopped mcapi with pid ${line}"
    done
}

function start_mcpub() {
    R=$(is_running "servers/mcpub/mcpub.js" "p $MC_PUB_SERVICE_PORT")
    if [ "$R" = "" ]; then
        echo "Starting mcpub ($SERVERTYPE)..."
        nodemon --watch servers/mcpub --watch servers/lib servers/mcpub/mcpub.js -p ${MC_PUB_SERVICE_PORT} > ${MC_LOG_DIR}/mcpub.out.${SERVERTYPE} 2>&1&
        sleep 1
    fi
}

function stop_mcpub() {
    echo "Stopping mcpub ($SERVERTYPE)..."
    ps -eo "pid,command" | grep "mcpub.js" | grep "p $MC_PUB_SERVICE_PORT" | grep -v grep | sed 's/^[ ]*//' | cut -f1 -d' ' | while read line
    do
        kill ${line}
        echo "  Stopped mcpub with pid ${line}"
    done
}

function start_mcmon() {
    R=$(is_running "servers/mcmon/main.js" "servertype $SERVERTYPE")
    if [ "$R" = "" ]; then
        echo "Starting mcmon ($SERVERTYPE)..."
        nodemon --watch servers/mcmon/main.js --watch servers/mcmon/src servers/mcmon/main.js --servertype $SERVERTYPE  > ${MC_LOG_DIR}/mcmon.out.${SERVERTYPE} 2>&1&
    fi
}

function stop_mcmon() {
    echo "Stopping mcmon ($SERVERTYPE)..."
    ps -eo "pid,command" | grep "servers/mcmon/main.js" | grep "servertype $SERVERTYPE" | grep -v grep | sed 's/^[ ]*//' | cut -f1 -d' ' | while read line
    do
        kill ${line}
        echo "  Stopped mcmon with pid ${line}"
    done
}

function start_redis() {
    R=$(is_running "redis-server" "${REDIS_PORT}")
    if [ "$R" = "" ]; then
        echo "Starting redis (${SERVERTYPE})..."
        redis-server --port ${REDIS_PORT} > ${MC_LOG_DIR}/redis.out.${SERVERTYPE} 2>&1&
        sleep 1
    fi
}

function stop_redis() {
    echo "Stopping redis ($SERVERTYPE)..."
    ps -eo "pid,command" | grep "redis-server" | grep "${REDIS_PORT}" | grep -v grep | sed 's/^[ ]*//' | cut -f1 -d' ' | while read line
    do
        kill ${line}
        echo "  Stopped redis-server with pid ${line}"
    done
}

function start_mcapid() {
    R=$(is_running "mcapid-${SERVERTYPE}" " ")
    if [ "$R" = "" ]; then
        echo "Start mcapid server (${SERVERTYPE})..."
        echo "${MCAPID_COMMAND}"
        (cd servers/mcapid; sh -c "${MCAPID_COMMAND}" > ${MC_LOG_DIR}/mcapid.out.${SERVERTYPE} 2>&1&)
        sleep 1
    fi
}

function stop_mcapid() {
    echo "Stopping mcapid (${SERVERTYPE})..."
    ps -eo "pid,command" | grep "mcapid-${SERVERTYPE}" | grep -v grep | sed 's/^[ ]*//' | cut -f1 -d' ' | while read line
    do
        kill ${line}
        echo "  Stopped mcapid server with pid ${line}"
    done
}

function check_nginx() {
    R=$(ps -eo "pid,command" | grep nginx | grep "worker process")
    if [ "$R" = "" ]; then
        echo "---------------- WARNING ----------------"
        echo "|  nginx does not appear to be running  |"
        echo "---------------- WARNING ----------------"
    fi
}

function start_servers() {
    echo Starting ${SERVERTYPE} servers...
    mkdir -p ${MC_LOG_DIR} 2> /dev/null

    if [ ${SERVERTYPE} = "test" -o ${SERVERTYPE} = "production" ]; then
        cd "${MC_DEPLOY_DIR}/backend"
    fi

    start_es
    start_faktory
    start_rethinkdb
    start_etl_faktory_worker
    start_etl_server
    start_mcapiserver
    start_mcstored
    start_mcapi
    start_mcpub
    start_mcmon
    start_redis
    start_mcapid

    disown -a
    echo Started ${SERVERTYPE}.
}

function stop_servers() {
    if [ "$TESTSERVER" = "p" ]; then
        echo "**** You are stopping PRODUCTION ****"
        read -p "Are you sure you want to do this [y/n]? " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 0
        else
            echo "Shutting down production in 5 seconds CTRL-C to abort..."
            sleep 5
        fi
    fi

    echo Stopping ${SERVERTYPE} servers....

    stop_es
    stop_faktory
    stop_etl_faktory_worker
    stop_etl_server
    stop_mcapiserver
    stop_mcstored
    stop_mcapi
    stop_mcpub
    stop_mcmon
    stop_mcapid
    stop_rethinkdb
    stop_redis

    echo Stopped ${SERVERTYPE}.
}

function stop_named_server() {
    case "$1" in
        mcapiserver)
            stop_mcapiserver
            ;;

        mcstored)
            stop_mcstored
            ;;

        mcapi)
            stop_mcapi
            ;;

        mcpub)
            stop_mcpub
            ;;

        es)
            stop_es
            ;;

        faktory)
            stop_faktory
            ;;

        mcetl)
            stop_etl_server
            ;;

        mcetlworker)
            stop_etl_faktory_worker
            ;;

        rethinkdb)
            stop_rethinkdb
            ;;

        mcmon)
            stop_mcmon
            ;;

        redis)
            stop_redis
            ;;

        mcapid)
            stop_mcapid
            ;;

        *)
            echo "Unknown server: $1"
            exit 1
            ;;
    esac
}

function restart_named_server() {
    stop_named_server $1
    case "$1" in
        mcapiserver)
            start_mcapiserver
            ;;

        mcstored)
            start_mcstored
            ;;

        mcapi)
            start_mcapi
            ;;

        mcpub)
            start_mcpub
            ;;

        es)
            start_es
            ;;

        faktory)
            start_faktory
            ;;

        mcetl)
            start_etl_server
            ;;

        mcetlworker)
            start_etl_faktory_worker
            ;;

        rethinkdb)
            start_rethinkdb
            ;;

        mcmon)
            start_mcmon
            ;;

        redis)
            start_redis
            ;;

        mcapid)
            start_mcapid
            ;;

        *)
            echo "Unknown server: $1"
            exit 1
            ;;
    esac

    disown -a
    echo Restarted Server $1 for server type ${SERVERTYPE}.
}

function ps_server_env() {
    SERVERTYPE=$1
    TESTSERVER=$2
    ES_CONTAINER=$3
    echo
    echo "===================== ${SERVERTYPE} (-${TESTSERVER}) ====================="
    echo
    setup_server_env

    echo "RethinkDB (${SERVERTYPE}):"
    ps -ef | grep rethinkdb | grep "driver-port $MCDB_PORT" | grep -v grep

    echo
    echo "REDIS (${SERVERTYPE}):"
    ps -ef | grep "redis-server" | grep "${REDIS_PORT}" | grep -v grep

    echo
    echo "Elasticsearch (${SERVERTYPE}):"
    R=$(docker_instance_running ${MC_ES_NAME})
    if [ "$R" != "" ]; then
        echo ${R}
    fi

    echo
    echo "Faktory (${SERVERTYPE}):"
    if [ "$(uname)" = "Darwin" ]; then
        ps -ef | grep faktory | grep -v tail | grep -v grep
    else
        R=$(docker_instance_running ${MC_FAKTORY_NAME})
        if [ "$R" != "" ]; then
            echo ${R}
        fi
    fi

    echo
    echo "MCETL server (${SERVERTYPE}):"
    ps -ef | grep mc_etlserver.py | grep -v grep

    echo
    echo "MCETL faktory worker (${SERVERTYPE}):"
    ps -ef | grep run_worker | grep -v grep

    echo
    echo "MCAPI Server (${SERVERTYPE}):"
    ps -ef | grep mcapiserver.py | grep "p $MC_SERVICE_PORT" | grep -v grep

    echo
    echo "MCAPI Node Server (${SERVERTYPE}):"
    ps -ef | grep mcapi.js | grep "p $MC_API_SERVICE_PORT" | grep -v grep

    echo
    echo "MCPUB Node Server (${SERVERTYPE}):"
    ps -ef | grep mcpub.js | grep "p $MC_PUB_SERVICE_PORT" | grep -v grep

    echo
    echo "MCSTORED Server (${SERVERTYPE}):"
    ps -ef | grep mcstored | grep "db-connect=localhost:$MCDB_PORT" | grep -v grep

    echo
    echo "MCMON Server (${SERVERTYPE}):"
    ps -ef | grep "servers/mcmon/main.js" | grep "servertype ${SERVERTYPE}" | grep -v grep

    echo
    echo "MCAPID Server (${SERVERTYPE}):"
    ps -ef | grep "mcapid-${SERVERTYPE}" | grep -v grep
}

function ps_servers() {
    if [ ${PS_ALL_SERVERS} = "t" ]; then
        export __SAVE_TESTSERVER=${TESTSERVER}
        export __SAVE_SERVERTYPE=${SERVERTYPE}

        ps_server_env "production" "p"
        ps_server_env "test" "t"
        ps_server_env "dev" "d"
        ps_server_env "unit" "u"

        export TESTSERVER=${__SAVE_TESTSERVER}
        export SERVERTYPE=${__SAVE_SERVERTYPE}
        setup_server_env
    else
        ps_server_env ${SERVERTYPE} ${TESTSERVER}
    fi
}

function config_file() {
    BASE="/etc/materialscommons/config"

    case "$SERVERTYPE" in
        production)
            echo Config file ${BASE}.prod
            ;;
        *)
            echo Config file ${BASE}.${SERVERTYPE}
            ;;
    esac
}

function show_env() {
    echo "======================== ${SERVERTYPE} ========================"
    echo
    echo " Environment and Setup Variables: "
    echo "   MCUSER:                 ${MCUSER}"
    echo "   MCDB_PORT:              ${MCDB_PORT}"
    echo "   MC_SERVICE_PORT:        ${MC_SERVICE_PORT}"
    echo "   MC_API_SERVICE_PORT:    ${MC_API_SERVICE_PORT}"
    echo "   MC_PUB_SERVICE_PORT:    ${MC_PUB_SERVICE_PORT}"
    echo "   RETHINKDB_HTTP_PORT:    ${RETHINKDB_HTTP_PORT}"
    echo "   RETHINKDB_CLUSTER_PORT: ${RETHINKDB_CLUSTER_PORT}"
    echo "   MCDB_DIR:               ${MCDB_DIR}"
    echo "   MCDIR:                  ${MCDIR}"
    echo "   MCFS_HTTP_PORT:         ${MCFS_HTTP_PORT}"
    echo "   MCDB_CONNECTION:        ${MCDB_CONNECTION}"
    echo "   MC_ES_URL:              ${MC_ES_URL}"
    echo "   MC_ES_NAME              ${MC_ES_NAME}"
    echo "   MCDB_FILE:              ${MCDB_FILE}"
    echo "   MCSTORE_SRC:            ${MCSTORE_SRC}"
    echo "   MC_LOG_DIR:             ${MC_LOG_DIR}"
    echo
    echo " Binary paths:"
    echo "   rethinkdb binary:       $(which rethinkdb)"
    echo "   mcapiserver.py binary:  ./mcapiserver.py"
    echo "   mcstored binary:        ${MCSTOREDBIN}"
    echo "   mcapi.js binary:        servers/mcapi/mcapi.js"
    echo "   mcpub.js binary:        servers/mcpub/mcpub.js"
    echo
    echo " Commands: "
    echo "   rethinkdb command:      rethinkdb --driver-port $MCDB_PORT --cluster-port $RETHINKDB_CLUSTER_PORT --http-port $RETHINKDB_HTTP_PORT --daemon"
    echo "   elasticsearch command:  docker start ${MC_ES_NAME}"
    if [ "$(uname)" = "Darwin" ]; then
        echo "   faktory command:        faktory"
    else
        echo "   faktory command:        docker start ${MC_FAKTORY_NAME}"
    fi
    echo "   mcapiserver.py command: mcapiserver.py -p $MC_SERVICE_PORT > ${MC_LOG_DIR}/mcapiserver.out.${SERVERTYPE} 2>&1&"
    echo "   mcstored command:       ${MCSTOREDBIN} --http-port=${MCFS_HTTP_PORT} --mcdir=${MCDIR} --db-connect=localhost:$MCDB_PORT --es-url=${MC_ES_URL} > ${MC_LOG_DIR}/mcstored.out.${SERVERTYPE} 2>&1&"
    echo "   mcapi.js command:       nodemon --watch servers/mcapi --watch servers/lib servers/mcapi/mcapi.js -p $MC_API_SERVICE_PORT > ${MC_LOG_DIR}/mcapi.out.${SERVERTYPE} 2>&1&"
    echo "   mcpub.js command:       nodemon --watch servers/mcpub --watch servers/lib servers/mcpub/mcpub.js -p $MC_PUB_SERVICE_PORT > /tmp/mcpub.out.${SERVERTYPE} 2>&1&"
    echo
    echo " OS Type"
    echo "   OS Type: $(uname)"
    echo
    echo " Environment Files:"
    echo "   Path: /etc/materialscommons/config.global"
    configfile=$(config_file)
    echo "   Path: ${configfile}"
    echo
}

function tail_servers() {
    D=${MC_LOG_DIR}
    ST=${SERVERTYPE}
    # Ensure files exist
    touch ${D}/mcapiserver.out.${ST} ${D}/mcstored.out.${ST} ${D}/mcapi.out.${ST} \
        ${D}/mcpub.out.${ST} ${D}/mcmon.out.${ST} ${D}/redis.out.${ST} \
        ${D}/mcapid.out.${ST} ${D}/mcetlserver.out.${ST} \
        ${D}/faktory.out.${ST} ${D}/mcetlfaktoryworker.out.${ST}
    tail -f ${D}/mcapiserver.out.${ST} -f ${D}/mcstored.out.${ST} -f ${D}/mcapi.out.${ST} \
        -f ${D}/mcpub.out.${ST} -f ${D}/mcmon.out.${ST} -f ${D}/redis.out.${ST} \
        -f ${D}/mcapid.out.${ST} -f ${D}/mcetlserver.out.${ST} \
        -f ${D}/faktory.out.${ST} -f ${D}/mcetlfaktoryworker.out.${ST}
}

function setup_deploy_dir() {
    if [ ${SERVERTYPE} = "test" -o ${SERVERTYPE} = "production" ]; then
        echo "Setting up ${MC_DEPLOY_DIR}..."
        mkdir -p "${MC_DEPLOY_DIR}/bin"
        mkdir -p "${MC_DEPLOY_DIR}/backend"
        mkdir -p "${MC_DEPLOY_DIR}/website"
    fi
}

function deploy_website() {
    mkdir ${MC_DEPLOY_DIR}/website
    cp -r ../website/mcapp.tar.gz "${MC_DEPLOY_DIR}/website"
    rm -rf "${MC_DEPLOY_DIR}/website/mcapp" "${MC_DEPLOY_DIR}/mcapp.tar.gz"
    (cd "${MC_DEPLOY_DIR}/website"; tar zxf mcapp.tar.gz)
}

function deploy_backend() {
    (cd ..; rm -rf "${MC_DEPLOY_DIR}/backend"; cp -r backend "${MC_DEPLOY_DIR}")
}

function deploy_mc() {
    export DB_BACKUP=/tmp/rethinkdb.update.${SERVERTYPE}.tar.gz
    echo "Deploying Materials Commons deployment..."
    echo "  Updating code for materialscommons.org and mcstore...."

    setup_deploy_dir

    if [ "$MC_BRANCH" != "" ]; then
        git checkout ${MC_BRANCH}
    fi
    git pull

    if [ "$MCSTORE_BRANCH" != "" ]; then
        (cd ${MCSTORE_SRC}; git checkout ${MCSTORE_BRANCH})
    fi
    (cd ${MCSTORE_SRC}; git pull)

    if [ "$BACKUP_DATABASE" = "t" ]; then
        echo "  Creating database backup..."
        rm -f ${DB_BACKUP}
        (rethinkdb dump -c localhost:${MCDB_PORT} -f ${DB_BACKUP})
        echo You can restore from the database backup at ${DB_BACKUP}
    fi

    if [ "$RUN_CONVERT" = "t" ]; then
        echo "  Performing optional conversion on database..."
        stop_named_server mcstored
        scripts/conversion/convert.py --port ${MCDB_PORT}
    fi

    echo "  Stopping servers..."
    stop_servers

    echo "  Updating server dependencies..."
    rm -f package-lock.json
    npm install

    (cd servers/mcapid; rm -f package-lock.json; npm install)

    echo "Updating website dependencies..."
    (cd ../website; rm -f package-lock.json)
    (cd ../website; npm install)
    (cd ../website; bower install)

    if [ "$SERVERTYPE" = "production" ]; then
        (cd ../website; ./build.sh)
    elif [ "$SERVERTYPE" = "test" ]; then
        (cd ../website; ./build.sh)
    fi

    if [ ${SERVERTYPE} = "test" -o ${SERVERTYPE} = "production" ]; then
        deploy_website
        deploy_backend
    fi

    echo "  All updates completed..."
    echo "  Starting servers..."
    start_servers
    ps_servers

    echo "Update completed."
    echo "If there are problems you can restore the previous version with mcservers restore command."
    echo "*** If you stopped nginx, please restart it ***"
}

function restore_mc() {
    RUN_CONVERT=f
    BACKUP_DATABASE=f
    MCSTORE_BRANCH=""
    MC_BRANCH=""
    if [ "$MC_RESTORE_BRANCH" != "" ]; then
        git checkout ${MC_RESTORE_BRANCH}
    fi

    if [ "$MCSTORE_RESTORE_BRANCH" != "" ]; then
        (cd ${MCSTORE_SRC}; git checkout ${MCSTORE_RESTORE_BRANCH})
    fi
    export MCDB_FILE=/tmp/rethinkdb.update.${SERVERTYPE}.tar.gz
    export REINIT=t
    update_mc
}

function setup_server_env() {
    if [ -z "$TESTSERVER" ]; then
        export TESTSERVER="d"
        export SERVERTYPE="dev"
    fi
    source ./env/${SERVERTYPE}.sh
}

function show_help() {
    echo "mcservers [start|stop|sr|ss|ps|env|tail|update|help]"
    echo "  The mcservers command with no arguments will run the ps command."
    echo "  If no environment flagged is specified mcservers defaults to -d"
    echo
    echo "    -h: Displays this help message and exits"
    echo "    -d: Dev environment"
    echo "    -t: Test environment"
    echo "    -p: Production environment"
    echo "    -n: Do not recompile mcstored"
    echo "    -r: Reload database from file pointed at by MCDB_FILE env variable"
    echo "    --ps: Show servers"
    echo "    --mc-restore-branch: Branch to checkout from materialscommons.org repo when using the restore command"
    echo "    --mcstore-restore-branch: Branch to checkout from mcstore repo when using the restore command"
    echo "    --mc-branch: Branch to checkout from materialscommons.org repo when using the restore command"
    echo "    --mcstore-branch: Branch to checkout from mcstore repo when using the update command"
    echo "    --run-convert: Runs the scripts/conversion/convert.py script when performing an update"
    echo "    --no-compile-mcstore: Doesn't recompile mcstore when starting it"
    echo "    --no-backup: Doesn't perform a backup of the database when performing an update"
    echo
    echo "  help: Displays this help message and exits."
    echo "  start [-d | -t | -p] [-n] [-r] [--ps]: Starts servers. Will only start servers not currently running."
    echo "  stop [-d | -t | -p] [--ps]: Stops all servers."
    echo "  sr|srestart <server-name>  [-d | -t | -p] [-n]: Restart the named server in the given environment- mcapiserver|mcstored|mcapi|mcpub|es."
    echo "  ss|sstop <server-name>  [-d | -t | -p]: Stop the named server in the given environment - mcapiserver|mcstored|mcapi|mcpub|es."
    echo "  ss <server-name>  [-d | -t | -p]: Stop the named server in the given environment - mcapiserver|mcstored|mcapi|mcpub|es."
    echo "  ps: Shows the status for all given services in all the environments."
    echo "  env: Shows the paths, environment variables, and other info for all the environments."
    echo "  tail [-d | -t | -p]: Tails all the logs for all servers for the given environment."
    echo "  deploy [-d | -t | -p] [-n] [-r]: Updates and deploys Materials Commons from the current branch for the given environment. Includes mcstore repository."
    echo "         [--mc-branch <branch>] [--mcstore-branch <branch>] [--no-backup] [--run-convert]"
    echo "  restore [-d | -t | -p]: Restores the previous update by reloading from the database backup and optionally checking out from the given branches."
    echo "          [--mc-restore-branch <branch>] [--mcstore-restore-branch <branch>]"
    exit 0
}

export MCDB_NAME="materialscommons"
export MCDB_TYPE="rethinkdb"

if [ -f /etc/materialscommons/config.global ]; then
    . /etc/materialscommons/config.global
fi

if [ "$MCUSER" = "" ]; then
    export MCUSER=${USER}
fi

export MCSTORE_SRC=$HOME/workspace/src/github.com/materials-commons/mcstore

# Set defaults
TESTSERVER="d"
SERVERTYPE="dev"
REINIT=f
RUN_CONVERT=f
MC_RESTORE_BRANCH=""
MCSTORE_RESTORE_BRANCH=""
MC_BRANCH=""
MCSTORE_BRANCH=""
COMPILE_MCSTORE=t
MC_SERVICE_NAME=""
BACKUP_DATABASE=t
SHOW_SERVERS=f
#PS_ALL_SERVERS=t
REDIS_PORT=6379

CMD=$1
shift

if [ "$CMD" = "sstop" ]; then
    MC_SERVICE_NAME=$1
    if [ "$MC_SERVICE_NAME" = "-h" ]; then
        show_help
    fi
    shift
elif [ "$CMD" = "ss" ]; then
    MC_SERVICE_NAME=$1
    if [ "$MC_SERVICE_NAME" = "-h" ]; then
        show_help
    fi
    shift
elif [ "$CMD" = "sr" ]; then
    MC_SERVICE_NAME=$1
    if [ "$MC_SERVICE_NAME" = "-h" ]; then
        show_help
    fi
    shift
elif [ "$CMD" = "srestart" ]; then
    MC_SERVICE_NAME=$1
    if [ "$MC_SERVICE_NAME" = "-h" ]; then
        show_help
    fi
    shift
elif [ "$CMD" = "-h" ]; then
    show_help
fi

while test $# -gt 0; do
    case "$1" in
        -h)
            show_help
            ;;
        --mc-restore-branch)
            shift
            MC_RESTORE_BRANCH=$1
            ;;
        --mcstore-restore-branch)
            shift
            MCSTORE_RESTORE_BRANCH=$1
            ;;
        --mc-branch)
            shift
            MC_BRANCH=$1
            ;;
        --mcstore-branch)
            shift
            MCSTORE_BRANCH=$1
            ;;
        --run-convert)
            RUN_CONVERT=t
            ;;
        -u)
            TESTSERVER=u
            SERVERTYPE="unit"
            PS_ALL_SERVERS=f
            ;;
        -d)
            TESTSERVER=d
            SERVERTYPE="dev"
            PS_ALL_SERVERS=f
            ;;
        -t)
            TESTSERVER=t
            SERVERTYPE="test"
            PS_ALL_SERVERS=f
            ;;
        -p)
            TESTSERVER=p
            SERVERTYPE="production"
            PS_ALL_SERVERS=f
            ;;
        --ps)
            SHOW_SERVERS=t
            ;;
        --no-compile-mcstore)
            COMPILE_MCSTORE=f
            ;;
        --no-backup)
            BACKUP_DATABASE=f
            ;;
        -r)
            REINIT=t
            ;;
    esac
    shift
done

setup_server_env

case "$CMD" in
    env)
        show_env
        ;;

    help)
        show_help
        ;;

    start)
        must_be_mcuser
        start_servers
        if [ "$SHOW_SERVERS" = "t" ]; then
            ps_servers
        fi
        ;;

    stop)
        must_be_mcuser
        stop_servers
        sleep 2
        if [ "$SHOW_SERVERS" = "t" ]; then
            ps_servers
        fi
        ;;

    srestart)
        must_be_mcuser
        restart_named_server ${MC_SERVICE_NAME}
        ;;

    sr)
        must_be_mcuser
        restart_named_server ${MC_SERVICE_NAME}
        ;;

    sstop)
        must_be_mcuser
        stop_named_server ${MC_SERVICE_NAME}
        ;;

    ss)
        must_be_mcuser
        stop_named_server ${MC_SERVICE_NAME}
        ;;

    ps)
        ps_servers
        ;;

    tail)
        tail_servers
        ;;

    restore)
        must_be_mcuser
        restore_mc
        ;;

    deploy)
        must_be_mcuser
        deploy_mc
        ;;

    -u)
        TESTSERVER=u
        SERVERTYPE="unit"
        PS_ALL_SERVERS=f
        ps_servers
        ;;

    -d)
        TESTSERVER=d
        SERVERTYPE="dev"
        PS_ALL_SERVERS=f
        ps_servers
        ;;

    -t)
        TESTSERVER=t
        SERVERTYPE="test"
        PS_ALL_SERVERS=f
        ps_servers
        ;;

    -p)
        TESTSERVER=p
        SERVERTYPE="production"
        PS_ALL_SERVERS=f
        ps_servers
        ;;

    "")
        TESTSERVER=d
        SERVERTYPE="dev"
        PS_ALL_SERVERS=f
        ps_servers
        ;;

    *)
        echo "Unknown command: $CMD"
        exit 1
        ;;
esac

check_nginx
