#!/bin/sh
OPTIND=1

TESTSERVER=false
while getopts "t" opt; do
    case "$opt" in
        t)
            TESTSERVER=true
            ;;
    esac
done

if [ $TESTSERVER = true ]; then
    export MCDB_DIR=/tmp
    export MC_SERVICE_PORT=5002
    export MCDB_PORT=30815
    export RETHINKDB_HTTP_PORT=8090
else
    export MCDB_PORT=28015
    export RETHINKDB_HTTP_PORT=8080
    export MC_SERVICE_PORT=5000
fi

echo Stopping servers....
RPID=$(ps -eo "%p:%c:%a" | grep rethinkdb | grep "driver-port $MCDB_PORT" | grep -v grep | head -1 | cut -f1 -d:)
kill $RPID
ps -eo "%p:%c:%a" | grep rest.py | grep "p $MC_SERVICE_PORT" | grep -v grep | cut -f1 -d: | while read line
do
    kill $line
done

if [ $TESTSERVER = true ]; then
    (cd $MCDB_DIR; rm -rf rethinkdb_data)
fi
echo Stopped.
