#!/bin/sh
OPTIND=1

TESTSERVER=false
while getopts "t" opt; do
    case "$opt" in
        t)
            TESTSERVER=true
            ;;
    esac
done

if [ $TESTSERVER = true ]; then
    export MC_SERVICE_PORT=5002
    export MCDB_PORT=30815
else
    export MCDB_PORT=28015
    export MC_SERVICE_PORT=5000
fi

echo "RethinkDB:"
ps -ef | grep rethinkdb | grep "driver-port $MCDB_PORT" | grep -v grep
echo
echo "MCAPI Server:"
ps -ef | grep mcapiserver.py | grep "p $MC_SERVICE_PORT" | grep -v grep
