#!/bin/sh
OPTIND=1

TESTSERVER=false
while getopts "t" opt; do
    case "$opt" in
        t)
            TESTSERVER=true
            ;;
    esac
done

if [ $TESTSERVER = true ]; then
    export MC_SERVICE_PORT=5002
    export MCDB_PORT=30815
    export MCDB_DIR=/tmp
    export RETHINKDB_HTTP_PORT=8090
    (cd $MCDB_DIR; rm -rf rethinkdb_data)
else
    export MCDB_PORT=28015
    export MC_SERVICE_PORT=5000
    export RETHINKDB_HTTP_PORT=8080
fi

echo Starting servers...
nohup ./rest.py -p $MC_SERVICE_PORT > /tmp/rest.out 2>&1&
(cd $MCDB_DIR; rethinkdb --driver-port $MCDB_PORT --http-port $RETHINKDB_HTTP_PORT --daemon)

if [ $TESTSERVER = true ]; then
    cp ../test_data/rethinkdb_dump_test_data.tar.gz $MCDB_DIR
    rethinkdb restore $MCDB_DIR/rethinkdb_dump_test_data.tar.gz --connect localhost:$MCDB_PORT
fi
echo Started.
