angular.module('materialscommons', [
    'ngSanitize',
    'ngMessages',
    'ngMaterial',
    'ui.router',
    'restangular',
    'ui.tree',
    'RecursionHelper',
    'md.data.table',
    'angular.filter',
    "hljs",
    'ui.bootstrap',
    'ngCkeditor',
    'angularUtils.directives.dirPagination',
    'ct.ui.router.extras.core', 'ct.ui.router.extras.transition',
    'ct.ui.router.extras.previous',
    'angular-timeline',
    'blockUI',
    'ngHandsontable',
    'angular-c3-simple',
    'dndLists',
    'ngFileUpload'
]);