import './mc-template-builder/template-units.service';
import './mc-template-builder/template-property-types.service';
import './mc-template-builder/mc-template-builder-properties.component';
import './mc-template-builder/mc-template-builder-description.component';
import './mc-template-builder/mc-template-builder-measurements.component';
import './mc-template-builder/mc-template-builder-review.component';
import './mc-template-builder/mc-template-builder-setup.component';
import './mc-template-builder/mc-template-builder-elements.component';
import './mc-template-builder/mc-template-builder.component';